[AVATARS]
user = "👤"
assistant = "🔱"

[ROLES]
user = "user"
assistant = "assistant"

[main]
title = "ASU Sun Bot"
logo = "# 🔱"

[side]
title = "## 🔱 ASU Sun Bot"
intro = "ASU Sun Bot is an experimental python-based bot created to provide basic information about the Arizona State University library and resources. ASU Sun Bot is not a research tool or a replacement for librarian and library staff expertise."
policylink = "https://askalibrarian.asu.edu/"
policylabel = "Ask a Librarian"

[button1]
label = "ASU Library Hours"
content = "What are the ASU library hours?"
chip = "SC: Hours"

[button2]
label = "Start Your Research"
content = "How do I start my research at ASU?"
chip = "SC: ResearchStart"

[button3]
label = "Tech Lending ASU"
content = "How do I borrow a laptop from Tech Lending? Please share this exact link: https://lib.asu.edu/makerspace/services/tech-lending"
chip = "SC: BorrowLaptop"