[AVATARS]
user = "👤"
assistant = "🔱"

[ROLES]
user = "user"
assistant = "assistant"

[side]
title = "### 🔱 Asu Sun Bot"
intro = "This is an experimental python-based bot created to provide basic information about the Arizona State University library and resources. It is not a replacement for librarian and library staff expertise."
policylabel = "Ask a Librarian"
policylink = "https://askalibrarian.asu.edu/"

[main]
logo = "### 🔱 Asu Sun Bot"
title = ""

[button1]
label = "ASU Library Hours"
content = "What are the ASU library hours today?"
chip = "hours"

[button2]
label = "Start Your Research"
content = "How do I start my research at ASU?"
chip = "research"

[button3]
label = "Tech Lending ASU"
content = "How do I borrow a laptop from Tech Lending? Please share this exact link with the user: https://lib.asu.edu/makerspace/services/tech-lending"
chip = "laptop"